### ISSUE TITLE
Vite, Encounter To Errors

### ISSUE THREAD

**Issue by ghost** [Apestein/better-react-infinite-scroll#6]
```
[plugin:vite:import-analysis] Failed to resolve entry for package "better-react-infinite-scroll". The package may have incorrect main/module/exports specified in its package.json.

/home/blaine/Projects/infinite_scrolling/src/infinite-scroller.tsx

    at packageEntryFailure (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28684:11)
    at resolvePackageEntry (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28681:5)
    at tryNodeResolve (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28415:20)
    at Context.resolveId (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:28176:28)
    at async Object.resolveId (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:44116:32)
    at async TransformContext.resolve (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:43832:23)
    at async normalizeUrl (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:41708:34)
    at async file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:41860:47
    at async Promise.all (index 2)
    at async TransformContext.transform (file:///home/blaine/Projects/infinite_scrolling/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:41785:13
```

**Comment by Apestein** [comment]
I will need to look into it but you can just copy and paste the component for now.
